language: php
sudo: required
 
matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t orangehrm/orangehrm-environment-images:prod-5.6 docker-image

install:
  - docker-compose up -d
  - composer install
  - docker ps

script:
  - php vendor/bin/codecept run unit
  - php vendor/bin/codecept run functional
  - php vendor/bin/codecept run acceptance

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"



